---
- name: Install default Apache Web Server
  hosts: staging_servers
  become: yes

  tasks:
  - name: Install Apache Web Server
    apt:
      name: apache2
      state: latest
      update_cache: yes
   
  - name: Start Apache and Enable it on every boot
    service:
     name: apache2
     state: started
     enabled: yes   
...