---
- name: Install Apache and upload new web page
  hosts: ya-vm-test1 
  become: yes

  roles:
    - role:
        name: deploy_apache_web
        when: ansible_system == "linux"
# remove ...

  vars:
    source_file: ./WebSite/index.j2
    destination_file: /var/www/html

  tasks:
  - name: Install Apache Web Server
    apt:
      name: apache2
      state: latest
      update_cache: yes

  - name: Generate index.html
    template:
      src: "{{ source_file }}"
      dest: "{{ destination_file }}/index.html"
      mode: 0554
    notify: Restart_Apache 
   
  - name: Start Apache and Enable it on every boot
    service:
     name: apache2
     state: started
     enabled: yes   

  handlers:
  - name: Restart_Apache
    service:
     name: apache2
     state: restarted

...