---
- name: Install Apache and upload new web page
  hosts: staging_servers
  become: yes

  vars:
    source_file: ./WebSite/index.html
    destination_file: /var/www/html

  tasks:
  - name: Install Apache Web Server
    apt:
      name: apache2
      state: latest
      update_cache: yes

  - name: Copy home page to Server
    copy:
     src: "{{ source_file }}"
     dest: "{{ destination_file }}"
     mode: 0554
    notify: Restart_Apache  
   
  - name: Start Apache and Enable it on every boot
    service:
     name: apache2
     state: started
     enabled: yes   

  handlers:
  - name: Restart_Apache
    service:
     name: apache2
     state: restarted
...